### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rominf** [datalyze-solutions/pandas-qt#1]
```
# sudo pip3 install pandas-qt
Downloading/unpacking pandas-qt
  Downloading pandas-qt-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pandas-qt/setup.py) egg_info for package pandas-qt
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pandas-qt/setup.py", line 13
        raise e, "install sip first (comming with PyQt4)"
               ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pandas-qt/setup.py", line 13

    raise e, "install sip first (comming with PyQt4)"

           ^

SyntaxError: invalid syntax
```

**Comment by sem-geologist** [comment]
It could be enough to rewrite ofending part as
```
raise Exception("install sip first...")
```
which works bowth on python 3.x and 2.7

**Comment by dmopalmer** [comment]
I am trying to get pandas-qt working with both Python3 and PySide.  (It is checked in to my dmopalmer/pandas-qt  Python3 branch)

**Comment by lucas993** [comment]
:+1:

**Comment by dmopalmer** [comment]
As I said on issue #2 

I just submitted a pull request #15  that supports all pythons (2.7 and 3.5), all interfaces (PySide, PyQt4, PyQt5).

It doesn't work perfectly. I am not a person who will make it work perfectly. It is an improvement.

**Comment by zbarge** [comment]
I've got a fork for this as well with some support for 3.5 - it will at least install...https://github.com/zbarge/QtPandas
