### ISSUE TITLE
pandas-qt install fails in python 3.5.2

### ISSUE THREAD

**Issue by draperjames** [datalyze-solutions/pandas-qt#17]
I just tried to install this on my machine using;

`pip install pandas-qt`

And I get the following error;

```
Collecting pandas-qt
  Using cached pandas-qt-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-g8dh04_y\pandas-qt\setup.py", line 15
        raise ImportError, "install sip first (comming with PyQt4)"
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
```
Please let me know if you need any more information.

**Comment by zbarge** [comment]
I fixed this you can clone my fork and help if you want.

https://github.com/zbarge/QtPandas

**Comment by zbarge** [comment]
@draperjames see above

**Comment by draperjames** [comment]
Thank you! I'm Excited to try it out. I'm installing now. 😺

**Comment by draperjames** [comment]
So I installed and and ran;

```
from pandasqt.views.CSVDialogs import CSVImportDialog

dialog = CSVImportDialog()
dialog.exec_()
```
And I got the following error;
```
C:\Anaconda3\lib\site-packages\pandasqt\encoding.py:21: UserWarning: Detector.Issues importing libmagic - got an error: [WinError 193] %1 is not a valid Win32 application
  warnings.warn("Detector.Issues importing libmagic - got an error: {}".format(e))
QWidget: Must construct a QApplication before a QPaintDevice
```
Any thoughts?

**Comment by draperjames** [comment]
Also I agree with your sentiments in #18 

> I think it would be fun to bring this package back to life and get some upgrades put into it.

I myself would like to help on the documentation front, however it seems as though the members of this project stopped merging pull requests some time ago. I'm new relatively new to Github so please forgive my ignorance, but would it be possible to create a new repo from your fork so I could contribute to it?
